// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-KytHi8rpHY3E6bBaaR2JwdgvybVdOc',
    appId: '1:145595303591:web:a2b19115c958df3336fd82',
    messagingSenderId: '145595303591',
    projectId: 'ttm-app-sheda',
    authDomain: 'ttm-app-sheda.firebaseapp.com',
    storageBucket: 'ttm-app-sheda.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsAZKq4tBH5F_iokC_jj5TjmPo4cjDEt4',
    appId: '1:145595303591:android:e70b0fe46f84cb5c36fd82',
    messagingSenderId: '145595303591',
    projectId: 'ttm-app-sheda',
    storageBucket: 'ttm-app-sheda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcpLGWMGEHXlNSwE_AJicZRYMNUmu4rLo',
    appId: '1:145595303591:ios:5190482dfccf569036fd82',
    messagingSenderId: '145595303591',
    projectId: 'ttm-app-sheda',
    storageBucket: 'ttm-app-sheda.firebasestorage.app',
    iosBundleId: 'com.example.teamTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcpLGWMGEHXlNSwE_AJicZRYMNUmu4rLo',
    appId: '1:145595303591:ios:5190482dfccf569036fd82',
    messagingSenderId: '145595303591',
    projectId: 'ttm-app-sheda',
    storageBucket: 'ttm-app-sheda.firebasestorage.app',
    iosBundleId: 'com.example.teamTaskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw-KytHi8rpHY3E6bBaaR2JwdgvybVdOc',
    appId: '1:145595303591:web:4f6a358ed3643b9436fd82',
    messagingSenderId: '145595303591',
    projectId: 'ttm-app-sheda',
    authDomain: 'ttm-app-sheda.firebaseapp.com',
    storageBucket: 'ttm-app-sheda.firebasestorage.app',
  );
}
